dotnet/source-indexer

src/Microsoft.SourceIndexer.Tasks/SelectProjects.cs, src/index/index.proj, src/index/repositories.props
Unblocks the source-indexer build: https://github.com/dotnet/core-eng/issues/2728
Note: MSBuild is frozen to a LKG commit from a few months ago. Its new build system freezes when I run it in this VSTS build, so I'm still looking into that.
Brings in this submodule PR: https://github.com/dotnet/SourceBrowser/pull/4
---
Old description:
> It would be better to remove this lookup completely (as mentioned in https://github.com/dotnet/core-eng/issues/2728), but this should at least unblock the builds for now by continuing the current runtime type lookup pattern.
> 
> I didn't have the exact VS version to try this out against, only a `15.6.0 Preview 3.0` vs. the build's `15.5.180.51428`, but it looks like the signature has only had one change after `func15`:
> …
=> Unblock official build on VS 15.5+

src/index/overwrite/index/SolutionExplorer.html
The generated solution explorer is a 35KB file, it takes browsers way too long to render the tree view from that.
=> Override the solution explorer with an empty one

src/index/index.proj, src/index/repositories.props
- Disable plugins.  They're not needed and are causing some exceptions.
- Disable API compat.  It's not needed and is resulting in a spew of failures in the error log.
- Disable building corefx packages.  They're not needed and suffer validation failures due to the partial build.
- Disable running corefxlab tests as part of build.
- Disable searching for WCF and MSBuild .vbprojs, as there aren't any.
- Disable including MSBuild test and sample projects, as they're not needed in the index.
cc: @alexperovich, @danmosemsft
=> Several source-indexer fixes

src/index/repositories.props
Build failing with:
```
src\index\index.proj(58,5): Error : Illegal characters in path.
at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
at System.IO.Path.GetFullPath(String path)
at Microsoft.SourceIndexer.Tasks.SelectProjects.<>c__DisplayClass10_0.<EvaluateItemInclude>b__3(String relative) in F:\a\_work\7\s\src\Microsoft.SourceIndexer.Tasks\SelectProjects.cs:line 61
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.<ExceptIterator>d__73`1.MoveNext()
at Microsoft.SourceIndexer.Tasks.SelectProjects.ExecuteCore() in …
```
=> Comment out iot addition that's breaking the build

src/index/index.proj
Currently, the build will fail if the repository path contains a space.  
This PR fixes that by adding quotes around the paths.
=> Fix build when path contains spaces

src/index/repositories.props
dotnet/runtime will remove the build helper scripts (coreclr.cmd, libraries.cmd, etc.) [soon](https://github.com/dotnet/runtime/pull/33756). Proactively updating the invocation here to prevent a break in the source-indexer.
=> Update dotnet/runtime build invocation

src/index/repositories.props
This can be reverted when https://github.com/dotnet/core-eng/issues/9537 is better addressed.
=> Temporarily remove projects still using 3.1 SDK

azure-pipelines.yml
This tries to work around tests in WCF asking for version 99.99.99 of the SDK.
=> Catch SDK installation failures on unreasonable versions

src/index/repositories.props
This resolves https://github.com/dotnet/source-indexer/issues/63. I also fixed the repo url for msbuild while I was here.
=> Add dotnet/performance to repositories.props

azure-pipelines.yml
Tweak the component governance scan configuration to scan only build data from source-indexer. This has the benefit of also ignoring data coming from the cloned and indexed repositories. Those repositories are managed separately. Also, their code here is only indexed, not executed.
=> Tweak CG to ignore cloned repositories

azure-pipelines.yml, src/SourceBrowser/src/SourceIndexServer/Models/AzureBlobFileSystem.cs, src/SourceBrowser/src/SourceIndexServer/SourceIndexServer.csproj
Nightly build [20220803.1](https://dev.azure.com/dnceng/internal/_build/results?buildId=1920322&view=results) failed because the build machines do not include .NET 6 by default. This adds it explicitly to the pipeline definition, and cleans-up use of older SDKs.
Test build happening in [20220803.3](https://dev.azure.com/dnceng/internal/_build/results?buildId=1921369&view=results).
=> Add .NET 6 to the build

src/index/repositories.props
The AzDo stage was already added to EF in https://github.com/dotnet/efcore/pull/30303/files
Fixes https://github.com/dotnet/source-indexer/issues/56
=> Add EF Core

src/SourceBrowser/src/BinLogParser/BinLogParser.csproj, src/SourceBrowser/src/HtmlGenerator/HtmlGenerator.csproj
Fix aspnetcore CI builds
`Unhandled exception. System.NotSupportedException: Unsupported log file format. Latest supported version is 16, the log file has version 17.`
This version supports 17
=> Update structured log viewer to latest

Directory.Packages.props, README.md, azure-pipelines-codeql.yml, azure-pipelines.yml, global.json, src/Microsoft.SourceIndexer.Tasks/Microsoft.SourceIndexer.Tasks.csproj, src/SourceBrowser/TestCode/Type.Forwardee/Type.Forwardee.csproj, src/SourceBrowser/TestCode/Type.Forwarder.Reference/Type.Forwarder.Reference.csproj, src/SourceBrowser/TestCode/Type.Forwarder/Type.Forwarder.csproj, src/SourceBrowser/TestCode/Type.Referencer/Type.Referencer.csproj, src/SourceBrowser/src/BinLogParser/BinLogParser.csproj, src/SourceBrowser/src/BinLogToSln/BinLogToSln.csproj, src/SourceBrowser/src/Common/Common.csproj, src/SourceBrowser/src/Directory.Packages.props, src/SourceBrowser/src/GitGlyph/GitGlyph.csproj, src/SourceBrowser/src/HtmlGenerator.Tests/HtmlGenerator.Tests.csproj, src/SourceBrowser/src/HtmlGenerator/HtmlGenerator.csproj, src/SourceBrowser/src/MEF/MEF.csproj, src/SourceBrowser/src/SourceIndexServer.Tests/SourceIndexServer.Tests.csproj, src/SourceBrowser/src/SourceIndexServer/Helpers.cs, src/SourceBrowser/src/SourceIndexServer/SourceIndexServer.csproj, src/UploadIndexStage1/UploadIndexStage1.csproj
In https://github.com/dotnet/arcade/pull/14172 we were seeing this issue:
```
Processing binlog artifacts/log/Debug/Build.binlog into solution at directory .source-index/stage1output
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at Microsoft.SourceBrowser.BinLogParser.BinLogCompilerInvocationsReader.<>c__DisplayClass1_0.<ExtractInvocations>b__0()
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor) …
```
=> Update projects to net8.0 and move to Central Package Management

azure-pipelines.yml
Build of my previous merge #130 indicate a later version of azcli is needed (perhaps because of the new service connection type?). So I bump those to the latest available on netcorenativeassets.
=> Bump version fo azcli and azcopy

azure-pipelines.yml
Former PR #131 wasn't quite the right fix. Both packages are now distributed only as MSI, but the scripts except zip archives. I missed that. 
Instead of going through the trouble of installing a different version, I'm opting instead to rely on the tools installed in the base image.
=> Fixup az tools in pipeline

azure-pipelines.yml
It's not entirely clear what the intent was behind this artifact, but it's been uploading every byte of every indexed repo for at least 3 years, for no discernible reason. If this causes a problem down the line, we might be better placed to understand what we _actually_ want uploaded, because I can't fathom a world where this right here is doing a thing we want as-is.
=> Don't upload 18 gigs of source code per-build

src/SourceBrowser/src/Directory.Packages.props, src/UploadIndexStage1/Program.cs, src/UploadIndexStage1/UploadIndexStage1.csproj
See https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet for list of credentials which are used, in order.
I bumped the version number since this is an ABI break (`-o` flag no longer works; new `-s`, `-c` and `-b` flags are needed, so changes to the Arcade template are needed)
=> New non-SAS version of blob upload

azure-pipelines.yml
VS msbuild seems incapable of dealing with the transitive dependencies of the new (CVE-free) versions of the Azure SDK assemblies, and fails the build when attempting to use the downloader task. Switch to using `DotNetCli@2` instead of `VSBuild@1`. The assemblies are still being built for net472, but the newer msbuild is happier resolving the things it needs to.
=> Run build with dotnet msbuild, not VS msbuild

src/SourceBrowser/src/BinLogToSln/Program.cs, src/SourceBrowser/src/HtmlGenerator/Program.cs
Projects in https://github.com/dotnet/runtime/tree/6437b4868b6c41c9dc0708470ff41079b3b46f78/src/libraries/shims/stubs should be treated same as ref.
=> Treat stubs projects same as ref

src/index/repositories.props
WCF has already been participating in in-build source index publishing to netsourceindexstage1 - but we haven't been ingesting that data. Stop building it ourselves, and consume the data we've been given.
=> Switch WCF to RepositoryV2

azure-pipelines.yml
This failed in CI for an unrelated reason, the actual validation slot changes seem good
=> Deploy non-main builds to a validation slot only, not staging->prod

src/SourceBrowser/src/HtmlGenerator/HtmlGenerator.csproj
This resolves a version compatibility problem where `Microsoft.Build.*` are loaded from VS, but `Microsoft.NET.StringTools` is loaded from the HtmlGenerator build directory, and because that assembly isn't correctly ABI-versioned, `Microsoft.NET.StringTools.FowlerNollVo1aHash` is missing and the HTML generation fails.
This issue was set up to fail in https://github.com/dotnet/source-indexer/pull/123 where the `ExcludeAssets="runtime"` was dropped from the `Microsoft.NET.StringTools` `PackageReference`, but didn't start actually failing until our CI machines were updated to VS 17.10.4+ (the version whose MSBuild has a hard dependency on the updated `Microsoft.NET.StringTools`, as per https://github.com/dotnet/msbuild/pull/9860)
Sample build failure: …
=> Use Microsoft.NET.StringTools from VS, not build

azure-pipelines.yml
This allows changes to auth-related things which don't break the production service.
=> Use non-prod storage account for validation builds

azure-pipelines.yml
Security changes on the Azure subscription side have blocked us from using the previous idiom for getting a temporary service principal credential. Instead, use the managed identity service connection directly during download of stage 1 artifacts.
CI build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2486246&view=results
=> Don't round-trip download through service principal login during stage 1 download

src/index/repositories.props
Validated on private, e.g. https://netsourceindex-validation.azurewebsites.net/#q=tensor works
=> Convert machinelearning repo to RepositoryV2

.github/workflows/dotnet.yml
@directhex just testing the most basic build, I want to know if it's even possible.
=> Add github workflow basic build yml

src/Microsoft.SourceIndexer.Tasks/DownloadStage1Index.cs, src/UploadIndexStage1/Program.cs, src/index/repositories.props
Without a configured listener, we get no info on console.
With it, we get a LOT of useful diagnostics, including burning questions like "what did DefaultAzureCredential actually do?"
`[Informational] Azure-Identity: DefaultAzureCredential.GetToken invoked. Scopes: [ https://storage.azure.com//.default ] ParentRequestId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx`
=> Actually add an Azure event listener

src/index/repositories.props
This is tested on https://netsourceindex-validation.azurewebsites.net/ along with some other inclusions.
=> Switch Winforms to RepositoryV2

src/index/index.proj
This makes it easier to test locally, since cloning V2 repos is fast and cloning V1 repos is very slow - but without this new conditional, removing V1 repos from repositories.props will cause the build to fail (it tries to run git operations on the source-indexer checkout directly, not on repository checkouts)
=> Don't execute CloneV1/CloneV2 unless Repository/RepositoryV2 are non-null

src/Microsoft.SourceIndexer.Tasks/DownloadStage1Index.cs, src/UploadIndexStage1/Program.cs
Turns out the problem was firewalling misconfiguration on the Azure side. Let's not leave lots of trace-level output turned on when we don't need it (but keep some of the better try{}catch{} changes)
=> Dial back debug verbosity

src/SourceBrowser/src/Directory.Packages.props
Fixing Component Governance alert due to a transitive dependency.
=> Fix CG alert around Microsoft.IO.Redist

src/SourceBrowser/src/SourceIndexServer/Helpers.cs
Attempt at fixing https://github.com/dotnet/source-indexer/issues/176
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2585139&view=results
=> Use enescaped string when calling Azure BlobClient

src/index/repositories.props
=> Add maui to source index

src/Microsoft.SourceIndexer.Tasks/DownloadStage1Index.cs, src/SourceBrowser/src/SourceIndexServer/Models/AzureBlobFileSystem.cs, src/UploadIndexStage1/Program.cs
.. and use ManagedIdentityCredential when clientId is provided.
Prompted by https://github.com/dotnet/dnceng/issues/5450
=> Use AzureCliCredential instead of DefaultAzureCredential

src/index/index.proj
SourceBrowser emits compilation diagnostics into `diagnostics.txt` files. Some can be seen directly like https://source.dot.net/Microsoft.CodeAnalysis/diagnostics.txt but others return 500 (they might be too long), e.g., https://source.dot.net/Microsoft.CodeAnalysis.CSharp/diagnostics.txt. By embedding the files into the binlog, we can inspect them from official CI builds at least.
This should simplify diagnosing issues like https://github.com/dotnet/source-indexer/issues/174.
Official build test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2697195&view=results
=> Embed diagnostics in binlog

src/SourceBrowser/src/BinLogToSln/Program.cs
This should fix errors like
<p>
<samp>
error CS0281: Friend access was granted by 'Microsoft.CodeAnalysis, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35', but the public key of the output assembly ('') does not match that specified by the InternalsVisibleTo attribute in the granting assembly.
<samp>
</p>
which break some references (i.e., some parts don't appear as links when they should be clickable).
When this is merged, new version of the BinLogToSln tool should be published (~not sure how~ looks like the official build does this automatically), because it actually runs as part of other repos' official builds.
=> Include signing key by BinLogToSln

src/SourceBrowser/src/BinLogToSln/BinLogToSln.csproj, src/SourceBrowser/src/BinLogToSln/Program.cs, src/SourceBrowser/src/Directory.Packages.props
Fixes missing source generated code. For example, go to `AliasAndExternAliasDirective` and observe missing link to `ExternAliasDirectiveSyntax` because that class is entirely source-generated, etc. See also https://source.dot.net/Microsoft.CodeAnalysis.CSharp/diagnostics.txt for a sample list of errors caused by source generated files missing.
<details>
<summary>Outdated info about commit 1</summary>
This fix includes the source generator DLLs to be packed in stage1output via BinLogToSln. That means they are loaded in the second stage. I guess that might cause errors (shouldn't be blocking, like no errors are during source indexing) when the Roslyn referenced by a source generator is newer (e.g., 5.0.0) than the Roslyn referenced by source indexer (e.g., 4.14.0). An alternative might be …
=> Support source-generated files
