.vscode/settings.json
src/index/index.proj
src/index/repositories.props

This change fixes the build issues that coreclr and msbuild were having.

Fix Build issues

---

src/index/repositories.props

CC. @danmosemsft, @eerhardt, @shauheen

Adding the machinelearning repo to the source indexer

---

src/index/repositories.props

Relates to https://github.com/dotnet/core-eng/issues/4610
@stephentoub @alexperovich

Fix corefx build command

---

src/index/repositories.props

cc: @danmosemsft, @alexperovich, @KirillOsenkov
https://github.com/dotnet/source-indexer/issues/24

Exclude ref projects for Windows Forms

---

src/index/repositories.props

Still need to figure out P2Ps but it's a start.

Add ASP.NET Core support

---

src/index/repositories.props

cc: @alexperovich, @ViktorHofer, @danmosemsft

Update source-indexer for dotnet/runtime

---

src/index/repositories.props

Fix ASP.NET urls after org move

---

src/index/repositories.props

Fixes https://github.com/dotnet/source-indexer/issues/60

Update runtime build command

---

src/SourceBrowser/TestCode/TestSolution_EdgeDriver_Tests/TestSolution_EdgeDriver_Tests.csproj
src/SourceBrowser/TestCode/TestSolution_MSTest_Tests/TestSolution_MSTest_Tests.csproj
src/SourceBrowser/TestCode/TestSolution_NUnit_Tests/TestSolution_NUnit_Tests.csproj
src/SourceBrowser/TestCode/TestSolution_XUnit_Tests/TestSolution_XUnit_Tests.csproj
src/SourceBrowser/src/SourceIndexServer.Tests/SourceIndexServer.Tests.csproj

Update Newtonsoft.Json version everywhere.

Pin Newtonsoft.Json version

---

azure-pipelines.yml
src/SourceBrowser/src/SourceIndexServer/SourceIndexServer.csproj

This dependabot bump broke one of the projects. Revert it for now, fix it when we sort through the rest of the Azure SDK upgrades.

Revert Azure.Storage.Blobs update

---

src/SourceBrowser/src/SourceIndexServer/Models/AzureBlobFileSystem.cs
src/SourceBrowser/src/SourceIndexServer/SourceIndexServer.csproj

Passes tests, and works on local run.

Update to released Azure Storage SDK

---

README.md
azure-pipelines-codeql.yml
azure-pipelines.yml
src/SourceBrowser/TestCode/TestSolution_EdgeDriver_Tests/TestSolution_EdgeDriver_Tests.csproj
src/SourceBrowser/TestCode/TestSolution_MSTest_Tests/TestSolution_MSTest_Tests.csproj
src/SourceBrowser/TestCode/TestSolution_NUnit_Tests/TestSolution_NUnit_Tests.csproj
src/SourceBrowser/TestCode/TestSolution_XUnit_Tests/TestSolution_XUnit_Tests.csproj
src/SourceBrowser/src/BinLogToSln/BinLogToSln.csproj
src/UploadIndexStage1/UploadIndexStage1.csproj

Upgrade to net6.0

---

azure-pipelines-codeql.yml

See https://github.com/dotnet/arcade/issues/11151 for context

Set TSAEnabled variable to enable automated reporting

---

azure-pipelines.yml
src/SourceBrowser/src/BinLogParser/BinLogParser.csproj
src/SourceBrowser/src/HtmlGenerator/HtmlGenerator.csproj

As reported on the FR channel, the current version used does not work with latest possible binlogs

Update structured log viewer to latest

---

src/SourceBrowser/src/BinLogParser/BinLogParser.csproj
src/SourceBrowser/src/HtmlGenerator/HtmlGenerator.csproj

The actual fix for https://github.com/dotnet/arcade/issues/11995

Update MSBuild.StructuredLogger to support binlog format v15

---

azure-pipelines.yml

Part of [dotnet/arcade#13312](https://github.com/dotnet/arcade/issues/13312).
Change deployment method to unbreak deployments.

Change appservice deployment method

---

src/SourceBrowser/src/SourceIndexServer/wwwroot/overview.html

Add a link to the Microsoft privacy policy and Terms of Use.

Add link to privacy policy

---

src/SourceBrowser/src/HtmlGenerator/HtmlGenerator.csproj

Should fix package downgrade errors

Microsoft.Build dependencies

---

azure-pipelines.yml

Use a new service connection for deployments to the new subscription

New subscription, new service connection

---

src/SourceBrowser/src/Directory.Packages.props

See https://github.com/dotnet/aspnetcore/pull/53698

Update to latest MSBuild.StructuredLogger

---

azure-pipelines.yml

This pipeline only runs on private from main anyway, so won't be CI'd here on GH

Convert pipeline to 1ES templates

---

azure-pipelines.yml
src/Microsoft.SourceIndexer.Tasks/DownloadStage1Index.cs
src/Microsoft.SourceIndexer.Tasks/Microsoft.SourceIndexer.Tasks.csproj
src/SourceBrowser/src/Directory.Packages.props
src/UploadIndexStage1/Program.cs
src/index/index.proj

Don't merge until we have a better solution for how to specify the account/container than "hardcoded in the csproj"

SAS-free stage1 blob download during indexing

---

azure-pipelines.yml
src/SourceBrowser/src/SourceIndexServer/Models/AzureBlobFileSystem.cs
src/SourceBrowser/src/SourceIndexServer/SourceIndexServer.csproj

This allows us to disable anonymous access to the storage account, in theory

Use Managed Identity in app service to access storage account

---

src/Microsoft.SourceIndexer.Tasks/DownloadStage1Index.cs
src/UploadIndexStage1/Program.cs

Hopefully this helps in figuring out https://github.com/dotnet/dnceng/issues/2974

Add lots of debug information to stage 1 uploader

---

src/index/repositories.props

Is this all we need?
Seems official build is working: https://dev.azure.com/dnceng/internal/_build/results?buildId=2501252&view=logs&j=316d5c15-0c50-544e-8051-e6b14a1ab674&t=5f89d526-390b-527e-aa70-cb89e574fd04

Add roslyn to index

---

azure-pipelines.yml

This should help track down https://github.com/microsoft/azure-pipelines-tasks/issues/20221

Enable verbose logging

---

global.json
src/SourceBrowser/src/Directory.Packages.props

Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2603680&view=results

Update 8.0 dependencies to latest
